<?php
/**
 * @file
 *   Implements the necessary hooks.
 */


/**
 * Implements hook_menu().
 */
function smileys_menu() {
  $items = array();
  $items['admin/config/content/smileys'] = array(
    'title' => 'Smileys',
    'description' => 'Customize your smileys.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('smileys_overview_form'),
    'access arguments' => array('administer smileys'),
    'file' => 'smileys.admin.inc',
  );
  $items['admin/config/content/smileys/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/config/content/smileys/settings'] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('smileys_settings_form'),
    'access arguments' => array('administer smileys'),
    'weight' => 0,
    'type' => MENU_LOCAL_TASK,
    'file' => 'smileys.admin.inc',
  );
  $items['admin/config/content/smileys/import'] = array(
    'title' => 'Import',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('smileys_import_form'),
    'access arguments' => array('administer smileys'),
    'weight' => 1,
    'type' => MENU_LOCAL_TASK,
    'file' => 'smileys.admin.inc',
  );
  return $items;
}


/**
 * Implements hook_theme().
 */
function smileys_theme() {
  return array(
    'smileys_overview_form' => array(
      'file' => 'smileys.admin.inc',
      'render element' => 'form',
    )
  );
}


/**
 * Implements hook_permission().
 */
function smileys_permission() {
  return array(
    'administer smileys' => array(
      'title' => t('Administer smileys'),
      'restrict access' => TRUE,
    ),
  );
}


/**
 * Implementation of hook_filter().
 */
function smileys_filter_info() {
  $filters['smileys'] = array(
    'title' => t('Replaces textual smileys inside posts with images.'),
    'process callback' => 'smileys_filter_process',
  );
  return $filters;
}


/**
 * Smileys filter process callback
 */
function smileys_filter_process($text, $filter, $format) {
  global $base_path;

  $smileys = db_query('SELECT * FROM {smileys} WHERE status=1')->fetchAll();

  $chunks = preg_split('#(</?(?:code|pre)[^>]*>)#i', $text, -1, PREG_SPLIT_DELIM_CAPTURE);

  $output = '';
  $ignore = 0;
  $packs_path = variable_get('smileys_path', drupal_get_path('module', 'smileys') . '/packs');
  foreach ($chunks AS $key => $chunk) {
    if ($chunk == '<code>' || $chunk == '<pre>') {
      $ignore++;
    }
    elseif ($chunk == '</code>' || $chunk == '</pre>') {
      $ignore--;
    }
    // There are no unclosed code and pre tags.
    elseif ($chunk && !$ignore) {
      foreach ($smileys AS $smiley) {
        $image = '<img src="' . $base_path . $packs_path . '/' . $smiley->uri . '" alt="smiley"/>';
        $chunk = str_replace(explode(' ', $smiley->acronyms), $image, $chunk);
      }
    }
    $output .= $chunk;
  }

  return $output;
}
