<?php

define('CUSTOM_ROOT', DRUPAL_ROOT . '/' . drupal_get_path('module', 'custom'));

// Core module integration.
require_once CUSTOM_ROOT . '/includes/book.inc';
require_once CUSTOM_ROOT . '/includes/comment.inc';
require_once CUSTOM_ROOT . '/includes/field.inc';
require_once CUSTOM_ROOT . '/includes/menu.inc';
require_once CUSTOM_ROOT . '/includes/system.inc';

// Contrib module integration.
require_once CUSTOM_ROOT . '/includes/smileys.inc';
